// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Property<Guid>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormaEntregaId")
                        .HasColumnType("integer");

                    b.Property<int>("PrecioTotal")
                        .HasColumnType("integer");

                    b.HasKey("ComandaId");

                    b.HasIndex("FormaEntregaId");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("Domain.Entities.ComandaMercaderia", b =>
                {
                    b.Property<int>("ComandaMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComandaMercaderiaId"));

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uuid");

                    b.Property<int>("MercaderiaId")
                        .HasColumnType("integer");

                    b.HasKey("ComandaMercaderiaId");

                    b.HasIndex("ComandaId");

                    b.HasIndex("MercaderiaId");

                    b.ToTable("ComandaMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.FormaEntrega", b =>
                {
                    b.Property<int>("FormaEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FormaEntregaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("FormaEntregaId");

                    b.ToTable("FormaEntrega");

                    b.HasData(
                        new
                        {
                            FormaEntregaId = 1,
                            Descripcion = "Salon"
                        },
                        new
                        {
                            FormaEntregaId = 2,
                            Descripcion = "Delivery"
                        },
                        new
                        {
                            FormaEntregaId = 3,
                            Descripcion = "Pedidos Ya"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.Property<int>("MercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MercaderiaId"));

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Precio")
                        .HasColumnType("integer");

                    b.Property<string>("Preparacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TipoMercaderiaId")
                        .HasColumnType("integer");

                    b.HasKey("MercaderiaId");

                    b.HasIndex("TipoMercaderiaId");

                    b.ToTable("Mercaderia");

                    b.HasData(
                        new
                        {
                            MercaderiaId = 1,
                            Imagen = "https://drive.google.com/uc?export=download&id=14T7uOtb9yIaukf7EvPw99ntbb4A5M2q8",
                            Ingredientes = "bastones de queso (6)",
                            Nombre = "deditos de queso",
                            Precio = 600,
                            Preparacion = "empanizar 6 bastones de queso y freirlos en abundante aceite",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 2,
                            Imagen = "https://drive.google.com/uc?export=download&id=1tTY1nVA9cxIm4NyRcadOC1sQQMAN577w",
                            Ingredientes = "papas (1), huevo (2), queso (100gr), jamon(100gr)",
                            Nombre = "tortilla de papa",
                            Precio = 1200,
                            Preparacion = "formar una tortilla de forma redonda y plana con huevo y trozos de papas, rellno de jamon y queso",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 3,
                            Imagen = "https://drive.google.com/uc?export=download&id=1JBK2cdZo-jimrJRYLYmMrvQQguh7PapL",
                            Ingredientes = "crema (30gr), ricota (200gr)",
                            Nombre = "sorrentinos de ricota",
                            Precio = 1500,
                            Preparacion = "pasta rellena en forma redonda con ricota y crema",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 4,
                            Imagen = "https://drive.google.com/uc?export=download&id=11VXVqMDgXd802UwA-u3PFtD-4MZDu5UA",
                            Ingredientes = "entrañas (1), limon (1), perejil fresco (50gr)",
                            Nombre = "entraña con papas fritas",
                            Precio = 2600,
                            Preparacion = "cocinar la entraña aderezada con limon y perejil en parrilla bien caliente con mucha brasa, freir las papas en aceite",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 5,
                            Imagen = "https://drive.google.com/uc?export=download&id=1c4XjtSEudmSoPSzAbXoTatNJ_RJ_lYe6",
                            Ingredientes = "salsa de tomate (100cc), albahaca (7), mozzarella (500gr)",
                            Nombre = "pizza",
                            Precio = 1300,
                            Preparacion = "untar salsa de tomate a la masa, agregar la mozzarella y cocinar hasta grtinar el queso, añadir las hojas de albahaca",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 6,
                            Imagen = "https://drive.google.com/uc?export=download&id=1dR8NBAgnHhdwu1FrjO8uLUA3dqjbsZ_z",
                            Ingredientes = "rebanadas de pan (4), fetas de queso (2), filetes de pollo (2), lechuga (2hojas), tomate (4rebanadas), mayonesa (30gr)",
                            Nombre = "sandwich club",
                            Precio = 800,
                            Preparacion = "tostar el pan, aderezarlo con mayonesa, colocar las fetas de queso, el tomate, los filetes de pollo y la lechuga",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 7,
                            Imagen = "https://drive.google.com/uc?export=download&id=12wd13076D1W6sYiPPNzpRU-rr_44WQXj",
                            Ingredientes = "tomate cherry rojo (100gr), tomate cherry amarillo (100gr), tomate pera (1), cebolla morada (1), diente de ajo (1), aceite de oliva (45ml), vinagre (20ml)",
                            Nombre = "panzanella italiana",
                            Precio = 600,
                            Preparacion = "cortar el tomate cherry rojo y amarillo por la mitad, cortar en rodajas el tomate pera y cortar la cebolla en juliana, picar el ajo y aderezar con vinagre y aceite de oliva",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaId = 8,
                            Imagen = "https://drive.google.com/uc?export=download&id=1Gx6OtOL24pGD2eUbd0vdlBrX8hVEcRyG",
                            Ingredientes = "azúcar (1cda), jugo de lima (30ml), menta fresca (5), ron blanco (60ml), cubos de hielo (4), soda (120ml)",
                            Nombre = "mojito",
                            Precio = 300,
                            Preparacion = "en un vaso, mezclar las hojas de menta con el jugo de lima y el azúcar. Agregar el ron junto con los cubos de hielo. Luego, echar la soda y revolver",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 9,
                            Imagen = "https://drive.google.com/uc?export=download&id=1mFg7nExEcLvb-TLd-CCXGtAqaE_B_ZQ4",
                            Ingredientes = "cerveza rubia (800cc), miel (2cdas), almíbar de frutas (2cdas)",
                            Nombre = "cerveza a la miel",
                            Precio = 600,
                            Preparacion = "en un vaso verter la cerveza rubia, colocar el almibar de frutas,la miel y revolver",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 10,
                            Imagen = "https://drive.google.com/uc?export=download&id=1hv4T7tOZjNO7QFod12BYqBbrHRFEwPxi",
                            Ingredientes = "leche (60ml), nata líquida (40ml), maizena (10gr), azúcar (10gr), mini galletas con pepitas de chocolate (3)",
                            Nombre = "crema de vainilla con cookies",
                            Precio = 400,
                            Preparacion = "en una cacerola calentar la leche, el azucar y la nata con la maicena hasta espesar, dejar enfriar en una compotera y servir con las mini cookies",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaId = 11,
                            Imagen = "https://drive.google.com/uc?export=download&id=1UNuJM9HQ1G06nC_O8Ewr_ccWBB-Rx2SE",
                            Ingredientes = "parmesano rallado (100gr), mozzarella rallada (200gr),Tomates cherry cortados en cuartos (200gr), albahaca (4hojas)",
                            Nombre = "empanadas caprese",
                            Precio = 400,
                            Preparacion = "cortamos la albahaca y la incorporamos en un bol junto a la mozzarella, el parmesano y los tomates cherry cortados en cuartos, salpimentamos, rellenamos las tapitas de empanadas y cocinamos",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 12,
                            Imagen = "https://drive.google.com/uc?export=download&id=1ZHtIgaEBYu8yh_4JlSVtfzVgGua489q2",
                            Ingredientes = "calabaza mediana (1), queso rallado (100gr), hierbas secas",
                            Nombre = "canastatitas de calabaza",
                            Precio = 500,
                            Preparacion = "hervir la calabaza para hacer un pure, mezclarla con queso rallado y las hierbas, formar canastas con tapitas de empanadas, rellenarlas y cocinar",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 13,
                            Imagen = "https://drive.google.com/uc?export=download&id=1u3ymdD7Yk8cP3LsRk39cl9i3wd13ch7Z",
                            Ingredientes = "ricota (500gr), huevo (1), harina (225gr)",
                            Nombre = "ñoquis de ricota",
                            Precio = 1200,
                            Preparacion = "colocar en un bol la ricota y el huevo, salpimentar, mezclar e integrar la harina, formar la masa y cortarla en cubitos y cocinarlos en agua hirviendo hasta que floten",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 14,
                            Imagen = "https://drive.google.com/uc?export=download&id=1pJNiFNZLp7B_vTCex_4Cslgw8_nFk-KG",
                            Ingredientes = "matambre (1), leche (1000ml), ajo (1), laurel (4)",
                            Nombre = "matambre a la parrilla",
                            Precio = 3000,
                            Preparacion = "macerar el matambre durante una noche cubierto de leche, las hojas de laurel y el ajo, llevar a una parrilla a fuego medio del lado de la grasa hasta que esté dorado, dar vuelta y dorar del lado restante",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 15,
                            Imagen = "https://drive.google.com/uc?export=download&id=1tph3tQXtdVtNjcIaaNXJMTawKemEvf1C",
                            Ingredientes = "anana (4rodajas), queso rallado (200gr), jamon cocido (400gr), queso mozzarella (300gr), salsa de tomate (250ml)",
                            Nombre = "pizza hawaiana",
                            Precio = 1300,
                            Preparacion = "cortar en trozos el jamón y en cubos el anana, untamos la masa con salsa de tomate, cubrir con el queso rallado, repartir por encima el jamón cocido y el anana y cocinar",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 16,
                            Imagen = "https://drive.google.com/uc?export=download&id=1sgRyeSS2z8dr39_3ZPeRCRRTkfISfFqz",
                            Ingredientes = "rebanadas de pan (4), jamon cocido (2fetas), salami (2fetas), lomo de cerdo asado (2lonchas), mostaza (10gr) ",
                            Nombre = "sandwich cubano",
                            Precio = 700,
                            Preparacion = "cortamos los panes por la mitad, untarlos con mostaza y colocar el jamón, el salami, el lomo, el queso",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 17,
                            Imagen = "https://drive.google.com/uc?export=download&id=1FtxE8-4g7XZ5Ltju1RqcNXFiE5g4QbqX",
                            Ingredientes = "lechuga (1), cebolla morada (1), zanahoria (1), tomates cherrys rojos (4)",
                            Nombre = "ensalada multicolor",
                            Precio = 500,
                            Preparacion = "cortar la lechuga y la cebolla morada en tiras, rallar la zanahoria, cortar los tomates por la mitad, aderezar y salpimentar",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaId = 18,
                            Imagen = "https://drive.google.com/uc?export=download&id=1l2ywuMdj-xuVOc-QOJFClgOWRxIPu4Xy",
                            Ingredientes = "melon (1/2), agua fria (1000ml), azucar (20gr), hielo (7)",
                            Nombre = "jugo de melon",
                            Precio = 300,
                            Preparacion = "en una licuadora agregar el melon cortado en cubos, el agua y el azucar, licuar hasta que quede homgeneo, servir en una jarra con los hielos",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 19,
                            Imagen = "https://drive.google.com/uc?export=download&id=18svxxGvBjCxuehiTiMwp9aqhTXe_7BQ5",
                            Ingredientes = "cerveza rubia (1 lata), gin (1 medida), jugo de limon (1 medida)",
                            Nombre = "cerveza con gin y limon",
                            Precio = 900,
                            Preparacion = "en un vaso verter la cerveza rubia, el gin y el jugo de limon y revolver",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 20,
                            Imagen = "https://drive.google.com/uc?export=download&id=1RtTHSy7oWWv3pYMGib8RS0FhKvFpczz_",
                            Ingredientes = "leche (60ml), claras de huevo (50ml), sobre de gelatina sin sabor (1), azúcar (10gr)",
                            Nombre = "crema de leche merengada",
                            Precio = 500,
                            Preparacion = "hervir la leche con el azúcar, disolvemos la gelatina en la mezcla, batir las claras a punto de nieve con un poco de azúcar, incorporar las claras y batir hasta que se integre todo y dejar enfriar en la heladera",
                            TipoMercaderiaId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoMercaderia", b =>
                {
                    b.Property<int>("TipoMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoMercaderiaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TipoMercaderiaId");

                    b.ToTable("TipoMercaderia");

                    b.HasData(
                        new
                        {
                            TipoMercaderiaId = 1,
                            Descripcion = "Entrada"
                        },
                        new
                        {
                            TipoMercaderiaId = 2,
                            Descripcion = "Minuta"
                        },
                        new
                        {
                            TipoMercaderiaId = 3,
                            Descripcion = "Pastas"
                        },
                        new
                        {
                            TipoMercaderiaId = 4,
                            Descripcion = "Parrilla"
                        },
                        new
                        {
                            TipoMercaderiaId = 5,
                            Descripcion = "Pizzas"
                        },
                        new
                        {
                            TipoMercaderiaId = 6,
                            Descripcion = "Sandwich"
                        },
                        new
                        {
                            TipoMercaderiaId = 7,
                            Descripcion = "Ensalada"
                        },
                        new
                        {
                            TipoMercaderiaId = 8,
                            Descripcion = "Bebidas"
                        },
                        new
                        {
                            TipoMercaderiaId = 9,
                            Descripcion = "Cerveza Artesanal"
                        },
                        new
                        {
                            TipoMercaderiaId = 10,
                            Descripcion = "Postres"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.HasOne("Domain.Entities.FormaEntrega", "FormaEntrega")
                        .WithMany("Comandas")
                        .HasForeignKey("FormaEntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaEntrega");
                });

            modelBuilder.Entity("Domain.Entities.ComandaMercaderia", b =>
                {
                    b.HasOne("Domain.Entities.Comanda", "Comanda")
                        .WithMany("ComandaMercaderias")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Mercaderia", "Mercaderia")
                        .WithMany("ComandaMercaderias")
                        .HasForeignKey("MercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Mercaderia");
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.HasOne("Domain.Entities.TipoMercaderia", "TipoMercaderia")
                        .WithMany("Mercaderias")
                        .HasForeignKey("TipoMercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Navigation("ComandaMercaderias");
                });

            modelBuilder.Entity("Domain.Entities.FormaEntrega", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.Navigation("ComandaMercaderias");
                });

            modelBuilder.Entity("Domain.Entities.TipoMercaderia", b =>
                {
                    b.Navigation("Mercaderias");
                });
#pragma warning restore 612, 618
        }
    }
}
